[features]
seeds = false
skip-lint = false
[programs.localnet]
testing_dlmm = "3m7k42SNzdf3iQfk3hMDvmiB7UmtJFbFFi23vYTU7ncn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrewnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
